name: test
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, ready_for_review, synchronize, converted_to_draft]

env:
  NX_CLOUD_DISTRIBUTED_EXECUTION: true

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.28.0
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - run: perl -i -p -e 's/postinstall/d/g;' package.json
      - run: pnpm install --frozen-lockfile
      - name: Fetch sonar-scanner
        run: |
          curl https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.5.0.2216-linux.zip --create-dirs -o /tmp/sonar-scanner-cli/sonar-scanner-cli.zip
          mkdir ~/.sonar
          unzip -q /tmp/sonar-scanner-cli/sonar-scanner-cli.zip -d ~/.sonar/native-sonar-scanner
      - run: pnpm exec nx-cloud start-ci-run
      - run: pnpm exec nx affected --target=build --parallel --max-parallel=4
        timeout-minutes: 10
      - run: pnpm exec nx affected --target=lint --parallel --max-parallel=4
        timeout-minutes: 10
      - run: pnpm exec nx affected --target=test --parallel --max-parallel=4
        timeout-minutes: 10
      - run: pnpm exec nx-cloud stop-all-agents
  agents:
    runs-on: ubuntu-latest
    name: Agent ${{ matrix.agent }}/4
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.28.0
      - uses: actions/setup-node@v2
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - name: Start Nx Agent ${{ matrix.agent }}
        run: pnpm exec nx-cloud start-agent
